### ISSUE TITLE
LEGS невозможно вставить точку перед активной

### ISSUE THREAD

**Issue by ponemetski** [ponemetski/extrinofms-issues#73]
- [x] Вот сейчас лечу на точку, хочу вставить перед ней другую - не могу, не вставляется...

- [x] иногда вываливается ошибка при попытке удалить активную точку: 
> Unhandled Exception: System.InvalidOperationException: Sequence contains no matching element
   at System.Linq.Enumerable.Single[TSource](IEnumerable`1 source, Func`2 predicate)
   at Fms.State.Nav.Route.OnProcessState(Double lat, Double lng, Double magvar, Single indicatedGroundSpeedKt, Single trueSpeedKt, Single windFromHeadingDeg, Single windSpeedKt, Single trackDeg, Int32 bankLimit) in /Users/Alex/source/git/extrinofms/src/Fms.State/Nav/Route.cs:line 596

- [x] вываливается ошибка при попытке вставить точку в пустое место образованное разрывом маршрута 
> Unhandled Exception: System.NullReferenceException: Object reference not set to an instance of an object.
   at Fms.State.Nav.Route.OnLegsAdded(Int32 posInLegs, INameLatLng to) in /Users/Alex/source/git/extrinofms/src/Fms.State/Nav/Route.cs:line 276

**Comment by soitanen** [comment]
вроде ок
